config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  get '/:locale' => 'homepage#show', constraints: {locale: /en/}
  get 'map_locations.json' => 'homepage#map_locations', :format => :json

  scope "(:locale)", locale: /en|pl/, constraints: {locale: /en|pl/} do
    namespace :admin do
      resources :posts, :except => [:edit]
      #resources :tags, :except => [:edit]
      resources :places, :except => [:edit]
      resources :locations, :except => [:edit]
      resources :homepage_photos, :except => [:edit]
      resources :homepage_settings, :except => [:edit]
      root 'posts#index'
    end
  end

  scope "(:locale)", locale: /en/, constraints: {locale: /en/} do
    get 's/:special' => 'posts#index', :as => :specific_posts
    get 'm/:place' => 'posts#index', :as => :placed_posts
    get 't/:tag' => 'posts#index', :as => :tagged_posts
    get 'm/:place/:id' => 'posts#show', :as => :placed_post
    get 't/:tag/:id' => 'posts#show', :as => :tagged_post
    get 'latest' => 'posts#index', :as => :latest_posts
    get ':id' => 'posts#show', :as => :post
  end
  root 'homepage#show'

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def show
    @homepage_photos = HomepagePhoto.order('created_at DESC').map {|photo| photo.image.url}
    @places = Place.with_translations(I18n.locale).order(:name).joins(:posts).select('places.*, place_translations.name').distinct
    @latest_post = Post.where(:published => true).order('created_at DESC').limit(1).first
  end

  def map_locations
    @locations = Location.safe.order('emailed_at DESC').map {|l| {
      :lat => l.lat,
      :lon => l.lon,
      :title => l.title,
      :date => l.emailed_at.to_s(:short),
      :description => l.description,
      :image => (l.image.file? ? l.image.url(:thumb) : nil),
      :vehicle_type => l.vehicle_type
    }}
    render :json => @locations
  end

end

app/views/homepage/show.html.haml
#homepage
  #homepage-title.image-gallery.fullscreen.background.parallax{:style => "background-image:url(\"#{@main_photo.image.url}\");", 'data-img-width' => @main_photo.image_width, 'data-img-height' => @main_photo.image_height, 'data-diff' => 200, 'data-images' => @homepage_photos }
    %h1
      = t('app_name')
    .scroll-pls
      %a.fa.fa-angle-double-down{:href => '#homepage-manifest'}
  #homepage-manifest.not-fullscren.parallax.box
    %h2
      %span= t('homepage.manifest1')
      %span= t('homepage.manifest2')
    %h3= t('homepage.subtitle')
    .scroll-pls
      .info= t('homepage.where_are_we')
      %a.fa.fa-angle-double-down{:href => '#homepage-map'}
  #homepage-map.init{:class => "#{'no-init' unless Rails.configuration.x.load_google_maps}"} Loading Google Maps...
  #homepage-travel-data.units-row
    #homepage-timer.data-section.unit-30{'data-days' => HomepageSetting.value(:days), 'data-when' => HomepageSetting.by_slug(:days).updated_at.strftime("%Y-%m-%d %H:%M"), :title => t('homepage.start_date')}
      %span.fa.fa-calendar
      %span.value= HomepageSetting.value(:days)
      = t('homepage.timer_description')
    #homepage-odometer-bike.data-section.unit-30{'data-km' => HomepageSetting.value(:odometer_bike), 'data-when' => HomepageSetting.by_slug(:odometer_bike).updated_at.strftime("%Y-%m-%d %H:%M")}
      %span.fa.fa-bicycle
      %span.value= HomepageSetting.value(:odometer_bike)
      %span.unit km
    #homepage-odometer-car.data-section.unit-30
      %span.fa.fa-car
      %span.value= HomepageSetting.value(:odometer_car)
      km
    #homepage-odometer-train.data-section.unit-30
      %span.fa.fa-train
      %span.value= HomepageSetting.value(:odometer_train)
      km
    #homepage-odometer-ship.data-section.unit-30
      %span.fa.fa-ship
      %span.value= HomepageSetting.value(:odometer_ship)
      km
    #homepage-odometer-plane.data-section.unit-30
      %span.fa.fa-plane
      %span.value= HomepageSetting.value(:odometer_plane)
      km
    .scroll-pls
      .info= t('homepage.whats_up')
      %a.fa.fa-angle-double-down{:href => '#homepage-latest'}
  - if @latest_post
    #homepage-latest.post-box.fullscreen.background.parallax{:style => "background-image:url(\"#{@latest_post.header_image.url}\");", 'data-img-width' => @latest_post.header_image_width, 'data-img-height' => @latest_post.header_image_height, 'data-diff' => 200, :class => "#{'inverted' if @latest_post.inverted_title}"}
      = link_to post_path(@latest_post) do
        - if @latest_post.s_letter
          .title-prefix= t('posts.specials.letter')
        %h2= @latest_post.title
        .post-summary= @latest_post.summary
  #homepage-post-list
    #homepage-all-posts-link.homepage-place-link
      = link_to t('homepage.latest_posts'), latest_posts_path
    %ul#homepage-posts-specials.blocks-3.blocks-mobile-50
      %li.homepage-special-link
        = link_to specific_posts_path(:special => 'movie') do
          %span.fa.fa-video-camera
          = t('posts.specials.movie')
      %li.homepage-special-link
        = link_to specific_posts_path(:special => 'photostory') do
          %span.fa.fa-camera
          = t('posts.specials.photostory')
      %li.homepage-special-link
        = link_to specific_posts_path(:special => 'letter') do
          %span.fa.fa-envelope
          = t('posts.specials.letter')
    .scroll-pls
      .info= t('homepage.post_categories')
      %a.fa.fa-angle-double-down{:href => '#homepage-posts-categories'}
  %ul#homepage-posts-categories.blocks-4.blocks-mobile-50

    - @places.each do |place|
      %li.homepage-place-link{:style => "background-image:url(\"#{place.posts.first.header_image.url(:medium)}\");"}
        = link_to place.name, placed_posts_path(:place => place.slug)
  = render 'shared/fb_like_page' unless Rails.env.development?
  = render 'shared/footer'
  - if Rails.configuration.x.load_google_maps
    - content_for :javascripts do
      = javascript_include_tag "//maps.google.com/maps/api/js?v=3.23&key=#{Rails.application.secrets.google_maps_api_key}&libraries=geometry&language=#{t('app_language')}&hl=#{t('app_language')}&region="
      = javascript_include_tag "//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"