config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  get '/:locale' => 'homepage#show', constraints: {locale: /en/}
  get 'map_locations.json' => 'homepage#map_locations', :format => :json

  scope "(:locale)", locale: /en|pl/, constraints: {locale: /en|pl/} do
    namespace :admin do
      resources :posts, :except => [:edit]
      #resources :tags, :except => [:edit]
      resources :places, :except => [:edit]
      resources :locations, :except => [:edit]
      resources :homepage_photos, :except => [:edit]
      resources :homepage_settings, :except => [:edit]
      root 'posts#index'
    end
  end

  scope "(:locale)", locale: /en/, constraints: {locale: /en/} do
    get 's/:special' => 'posts#index', :as => :specific_posts
    get 'm/:place' => 'posts#index', :as => :placed_posts
    get 't/:tag' => 'posts#index', :as => :tagged_posts
    get 'm/:place/:id' => 'posts#show', :as => :placed_post
    get 't/:tag/:id' => 'posts#show', :as => :tagged_post
    get 'latest' => 'posts#index', :as => :latest_posts
    get ':id' => 'posts#show', :as => :post
  end
  root 'homepage#show'

end

app/models/location.rb
class Location < ActiveRecord::Base

  VEHICLE_TYPES = ['bike', 'car', 'boat', 'plane', 'train']

  validates :lat, :lon, :emailed_at, :presence => true

  scope :safe, -> { where(["emailed_at < ?", Time.now - 4.hours]) }

  has_attached_file :image,
    :styles => { :thumb => '118x100#', :medium => '400x300#', :original => '1600' }

  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  def to_s
    "#{lat.round(3)}, #{lon.round(3)} (#{emailed_at.to_s(:short)})"
  end

  def vehicle_name
    VEHICLE_TYPES.at(vehicle_type)
  end
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < Admin::BaseController

  respond_to :html, :json

  before_action :set_location, only: [:show, :update, :destroy]

  def index
    @locations = Location.order('emailed_at DESC').page(params[:page]).per(60)
    respond_with(@locations)
  end

  def show
    respond_with(@location)
  end

  def new
    @location = Location.new
    respond_with(@location)
  end

  def create
    @location = Location.new(permitted_params)
    @location.save
    respond_with(@location, :action => :show, :location => admin_locations_path)
  end

  def update
    @location.update(permitted_params)
    if params[:commit] == 'Save and edit next'
      @next_location = Location.order(:emailed_at).where(["emailed_at > ?", @location.emailed_at]).limit(1).first
    elsif params[:commit] == 'Save and edit previous'
      @next_location = Location.order('emailed_at DESC').where(["emailed_at < ?", @location.emailed_at]).limit(1).first
    end
    if @next_location
      respond_with(@location, :action => :show, :location => admin_location_path(@next_location))
    else
      respond_with(@location, :action => :show, :location => admin_locations_path)
    end
  end

  def destroy
    @location.destroy
    respond_with(@location, :action => :show, :location => admin_locations_path)
  end

  private
  def set_location
    @location = Location.find(params[:id])
  end

  def permitted_params
    params.require(:location).permit(:lat, :lon, :emailed_at, :image, :vehicle_type, :title, :description)
  end
end

app/views/admin/locations/_form.html.haml
= simple_form_for [:admin, @location] do |f|

  %fieldset
    %legend Required data
    = f.input :lat, :as => :string, input_html: { class: 'width-50' }
    = f.input :lon, :as => :string, input_html: { class: 'width-50' }
    = f.input :emailed_at, :as => :string, input_html: { class: 'width-50' }

  %fieldset
    %legend Additional content
    = f.input :title, input_html: { class: 'width-100' }
    = f.input :description, :as => :text
    = f.input :vehicle_type, collection: [['bike', 0], ['car', 1], ['boat', 2], ['plane', 3], ['train', 4]], prompt: false, input_html: { class: 'width-50' }
    - if @location.image.file?
      .input-image-preview= image_tag @location.image.url(:thumb)
    = f.input :image

  .actions
    = f.submit 'Save and edit previous', :class => 'btn btn-big btn-blue'
    = f.submit 'Save', :class => 'btn btn-big btn-blue'
    = f.submit 'Save and edit next', :class => 'btn btn-big btn-blue'

app/views/admin/locations/index.html.haml
%table#admin-locations
  %thead
    %tr
      %th{:colspan => 2}= link_to 'New Location', new_admin_location_path, :class => 'btn btn-blue'

      %th{:colspan => 3}= paginate @locations
    %tr
      %th Lat
      %th Lon
      %th Date
      %th Vehicle
      %th.actions &nbsp;
  %tbody
    - @locations.each do |location|
      %tr
        %td= location.lat.round(6)
        %td= location.lon.round(6)
        %td= location.emailed_at.to_s(:short)
        %td= location.vehicle_name
        %td.actions
          = link_to 'Edit', [:admin, location], :class => 'btn btn-smaller'
          = link_to 'Destroy', [:admin, location], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-smaller btn-red'

  %tfoot
    %tr
      %th{:colspan => 2}= link_to 'New Location', new_admin_location_path, :class => 'btn btn-blue'
      %th{:colspan => 3}= paginate @locations

app/views/admin/locations/new.html.haml
%h1 New Location

= render 'form'
= link_to 'Back', admin_locations_path, :class => 'btn'

app/views/admin/locations/show.html.haml
= render 'form'

= link_to 'Destroy', [:admin, @location], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-red'
= link_to 'Back', admin_locations_path, :class => 'btn'