config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  get '/:locale' => 'homepage#show', constraints: {locale: /en/}
  get 'map_locations.json' => 'homepage#map_locations', :format => :json

  scope "(:locale)", locale: /en|pl/, constraints: {locale: /en|pl/} do
    namespace :admin do
      resources :posts, :except => [:edit]
      #resources :tags, :except => [:edit]
      resources :places, :except => [:edit]
      resources :locations, :except => [:edit]
      resources :homepage_photos, :except => [:edit]
      resources :homepage_settings, :except => [:edit]
      root 'posts#index'
    end
  end

  scope "(:locale)", locale: /en/, constraints: {locale: /en/} do
    get 's/:special' => 'posts#index', :as => :specific_posts
    get 'm/:place' => 'posts#index', :as => :placed_posts
    get 't/:tag' => 'posts#index', :as => :tagged_posts
    get 'm/:place/:id' => 'posts#show', :as => :placed_post
    get 't/:tag/:id' => 'posts#show', :as => :tagged_post
    get 'latest' => 'posts#index', :as => :latest_posts
    get ':id' => 'posts#show', :as => :post
  end
  root 'homepage#show'

end

app/models/place.rb
class Place < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged
  has_many :posts

  validates :name, :slug, :presence => true

  translates :name, :description, :fallbacks_for_empty_translations => true

  def should_generate_new_friendly_id?
    new_record? || super
  end
end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < Admin::BaseController

  respond_to :html, :json

  before_action :set_place, only: [:show, :update, :destroy]

  def index
    @places = Place.order('created_at DESC')
    respond_with(@places)
  end

  def show
    respond_with(@place)
  end

  def new
    render '/admin/shared/invalid_locale' and return if I18n.locale != I18n.default_locale
    @place = Place.new
    respond_with(@place)
  end

  def create
    @place = Place.new(permitted_params)
    @place.save
    respond_with(@place, :action => :show, :location => admin_places_path)
  end

  def update
    @place.update(permitted_params)
    respond_with(@place, :action => :show, :location => admin_places_path)
  end

  def destroy
    @place.destroy
    respond_with(@place, :action => :show, :location => admin_places_path)
  end

  private
  def set_place
    @place = Place.friendly.find(params[:id])
  end

  def permitted_params
    params.require(:place).permit(:name, :slug, :description)
  end
end

app/views/admin/places/_form.html.haml
= simple_form_for [:admin, @place] do |f|

  %fieldset
    %legend Edit place
    = f.input :name, input_html: { class: 'width-50' }
    = f.input :slug, input_html: { class: 'width-50' }
    = f.input :description, :as => :text, :label => 'Keywords'

  .actions
    = f.submit 'Save', :class => 'btn btn-big btn-blue'

app/views/admin/places/index.html.haml
%ul#admin-places.blocks-5
  - @places.each do |place|
    %li= link_to place.name, [:admin, place], :class => 'btn btn-big'

= link_to 'New Place', new_admin_place_path, :class => 'btn btn-blue'

app/views/admin/places/new.html.haml
%h1 New Place

= render 'form'
= link_to 'Back', admin_places_path, :class => 'btn'

app/views/admin/places/show.html.haml
= render 'form'

= link_to 'Destroy', [:admin, @place], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-red'
= link_to 'Back', admin_places_path, :class => 'btn'