config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  get '/:locale' => 'homepage#show', constraints: {locale: /en/}
  get 'map_locations.json' => 'homepage#map_locations', :format => :json

  scope "(:locale)", locale: /en|pl/, constraints: {locale: /en|pl/} do
    namespace :admin do
      resources :posts, :except => [:edit]
      #resources :tags, :except => [:edit]
      resources :places, :except => [:edit]
      resources :locations, :except => [:edit]
      resources :homepage_photos, :except => [:edit]
      resources :homepage_settings, :except => [:edit]
      root 'posts#index'
    end
  end

  scope "(:locale)", locale: /en/, constraints: {locale: /en/} do
    get 's/:special' => 'posts#index', :as => :specific_posts
    get 'm/:place' => 'posts#index', :as => :placed_posts
    get 't/:tag' => 'posts#index', :as => :tagged_posts
    get 'm/:place/:id' => 'posts#show', :as => :placed_post
    get 't/:tag/:id' => 'posts#show', :as => :tagged_post
    get 'latest' => 'posts#index', :as => :latest_posts
    get ':id' => 'posts#show', :as => :post
  end
  root 'homepage#show'

end

app/views/admin/shared/_locale_box.html.haml
.tools-alert.tools-alert-yellow.right
  You are currently editing content in:
  %span.locale_sym= I18n.locale.to_s
  | switch to
  %span.locale_sym= switch_locale_link

app/views/admin/shared/_navbar.html.haml
%nav#admin-main-navbar.navbar
  %ul
    %li
      = link_to 'Posts', admin_posts_path
    %li
      = link_to 'Places', admin_places_path
    %li
      = link_to 'Locations', admin_locations_path
    %li
      = link_to 'Homepage Photos', admin_homepage_photos_path
    %li
      = link_to 'Homepage Data', admin_homepage_settings_path
    %li
      = link_to 'Public Homepage', root_path

app/views/admin/shared/invalid_locale.html.haml
.tools-alert.tools-alert-red
  When creating new content you must use the default locale!
  Switch to
  %span.locale_sym= switch_locale_link

= link_to 'Back', :back, :class => 'btn'